# Numpy Basics

### Install numpy

In [1]:
#!pip3 install numpy

### Import numpy

In [2]:
import numpy as np

### Initialise a ndarray from a python list

In [3]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [4]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([[1, 2, 3], [2, 3, 4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
a[0]

array([1, 2, 3])

### Some important methods to initialise ndarrays

In [7]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(4)

array([6.93239118e-310, 0.00000000e+000, 1.75922468e-316, 1.75922468e-316])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

### Generate a range of numbers from start to end with some step size

In [12]:
np.arange(2, 21, 4)

array([ 2,  6, 10, 14, 18])

### Generate k numbers from start to end

In [13]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

### Numpy array data type (dtype)

In [14]:
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

### add and sort elements

In [15]:
a = np.array([3, 4, 5, 2, 3,7, 1])

In [16]:
b = np.sort(a)
b

array([1, 2, 3, 3, 4, 5, 7])

#### List in python '+' will concatinate

In [17]:
a = [ 1, 2, 3, 4]
b = [5, 6, 7, 8]
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [19]:
a ** 2

array([ 1,  4,  9, 16])

In [20]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Size Shape and dimention of an array

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])

Shape => (2, 3)
Size => 6
Dim => 2

In [22]:
a.shape

(2, 3)

In [23]:
a.size

6

In [24]:
a.ndim

2

### Reshape a  NP array

In [25]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
b = a.reshape(4, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
b.reshape(b.size)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Creating a New Axis 

In [28]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
a.shape

(10,)

In [30]:
a[0]

1

In [31]:
b = a[np.newaxis, :]
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [32]:
b.shape

(1, 10)

In [33]:
b[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
c = np.arange(1, 50)

### Transpose and fliping a matrix

In [35]:
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
a.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [37]:
np.flip(a, axis = 0)

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [38]:
np.flip(a, axis = 1)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

### Using np.ones to geerate any constant value matrix

In [39]:
(np.ones(25) * 3.14).reshape(5, 5)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

## Indexing and Slicing

In [40]:
a = np.array([1, 2, 3, 4, 5])

In [41]:
a[0]

1

In [42]:
a[0 : 3]

array([1, 2, 3])

In [43]:
a[1:]

array([2, 3, 4, 5])

In [44]:
a[:3]

array([1, 2, 3])

In [45]:
a = np.arange(1000)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [46]:
a[5 : -5]

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
       148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
       161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173,
       174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 18

In [47]:
np.concatenate((a[:5], a[-5:]))

array([  0,   1,   2,   3,   4, 995, 996, 997, 998, 999])

### Funny broadcasting matrix example

In [48]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [49]:
b = np.zeros(25).reshape(5, 5)
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
b + a

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [51]:
c = (np.arange(0, 5) * 10).reshape(5, 1)

In [52]:
c

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [53]:
(b + a + c)

array([[ 1.,  2.,  3.,  4.,  5.],
       [11., 12., 13., 14., 15.],
       [21., 22., 23., 24., 25.],
       [31., 32., 33., 34., 35.],
       [41., 42., 43., 44., 45.]])

In [54]:
(b + a + c).reshape(25)

array([ 1.,  2.,  3.,  4.,  5., 11., 12., 13., 14., 15., 21., 22., 23.,
       24., 25., 31., 32., 33., 34., 35., 41., 42., 43., 44., 45.])

### Relational Operation based slicing 

In [55]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [56]:
a[a <= 4]

array([1, 2, 3, 4])

In [57]:
a = np.arange(1000)

In [58]:
np.concatenate((a[:5], a[-5:]))

array([  0,   1,   2,   3,   4, 995, 996, 997, 998, 999])

In [59]:
a[(a < 5) | (a > 995)]

array([  0,   1,   2,   3,   4, 996, 997, 998, 999])

In [60]:
a[(a % 2 == 0) & (a % 3 == 0)]

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 102, 108, 114, 120, 126, 132, 138, 144, 150,
       156, 162, 168, 174, 180, 186, 192, 198, 204, 210, 216, 222, 228,
       234, 240, 246, 252, 258, 264, 270, 276, 282, 288, 294, 300, 306,
       312, 318, 324, 330, 336, 342, 348, 354, 360, 366, 372, 378, 384,
       390, 396, 402, 408, 414, 420, 426, 432, 438, 444, 450, 456, 462,
       468, 474, 480, 486, 492, 498, 504, 510, 516, 522, 528, 534, 540,
       546, 552, 558, 564, 570, 576, 582, 588, 594, 600, 606, 612, 618,
       624, 630, 636, 642, 648, 654, 660, 666, 672, 678, 684, 690, 696,
       702, 708, 714, 720, 726, 732, 738, 744, 750, 756, 762, 768, 774,
       780, 786, 792, 798, 804, 810, 816, 822, 828, 834, 840, 846, 852,
       858, 864, 870, 876, 882, 888, 894, 900, 906, 912, 918, 924, 930,
       936, 942, 948, 954, 960, 966, 972, 978, 984, 990, 996])

In [61]:
(a % 2 == 0)

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,

In [62]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
a[2:, :3]

array([[10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

### Sum elements in matrix

In [64]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
a.sum()

300

In [66]:
a.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [67]:
a.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

### Stacking Matrics

In [68]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [71]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [72]:
np.hstack((a, b))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

### Slicing a matrix

#### Equal split

In [73]:
a = np.arange(1, 25).reshape(2, 12)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [74]:
np.hsplit(a, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [75]:
b = np.arange(1, 33).reshape(8, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [76]:
np.vsplit(b, 4)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

### Column / Row specified split

In [77]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [78]:
np.hsplit(a, (4,))

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [79]:
np.vsplit(b, (3, 4))

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

### View and copy()

In [80]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [81]:
a = b[0, : ]
a

array([1, 2, 3, 4])

In [82]:
a[0] = 100
a

array([100,   2,   3,   4])

In [83]:
b

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32]])

In [84]:
splits = np.vsplit(b, 2)
splits

[array([[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [85]:
first = splits[0]

In [86]:
first[0, 1] = 200

In [87]:
b

array([[100, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32]])

In [88]:
b2 = b.copy()
b2

array([[100, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32]])

In [89]:
b2[0, 2] = 300
b2

array([[100, 200, 300,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32]])

In [90]:
b

array([[100, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32]])

### Min and Max

In [91]:
b.min()

3

In [92]:
b.max()

200

###  (ASSIGNMENT) Create a list of numbers generated from a numpy matrix where every number in list was min in row and max in column

In [93]:
a [
    [11, 112, 113, 114],
    [10, 22, 3, 1],
    [1, 2, 3, 3],
]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

### Generate Random Numbers

In [ ]:
rng = np.random.default_rng()

In [ ]:
rng.random(5)

In [ ]:
rng.random(5)

In [ ]:
rng.random((5, 3))

In [ ]:
 mat = rng.integers(1, 5, size = (5, 5))

### Unique items

In [ ]:
a = np.array([[1, 1, 2, 3, 3], [1, 1, 2, 4, 4]])
a

In [ ]:
np.unique(a)

### Flatten and ravel

In [ ]:
a = np.arange(1, 26).reshape(5, 5)
a

In [ ]:
x1 = a.flatten()
x1

In [ ]:
x1[0] = 100
x1

In [ ]:
a

In [ ]:
x2 = a.ravel()
x2

In [ ]:
x2[0] = 100
x2

In [ ]:
a

### Save and Load numpy matrix

In [ ]:
a

In [ ]:
np.save('weights', a)

In [ ]:
z = np.load('weights.npy')
z

In [ ]:
np.savetxt('weights.csv', a)

In [ ]:
np.loadtxt('weights.csv')