In [20]:
import numpy as np
import pandas as pd

In [21]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [22]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [23]:
dates = pd.date_range('20230228', periods = 6)
dates

DatetimeIndex(['2023-02-28', '2023-03-01', '2023-03-02', '2023-03-03',
               '2023-03-04', '2023-03-05'],
              dtype='datetime64[ns]', freq='D')

In [24]:
rng = np.random.default_rng()

In [25]:
nums = rng.integers(10, size = (6, 4))
nums

array([[4, 0, 0, 6],
       [1, 4, 4, 2],
       [6, 5, 2, 5],
       [0, 4, 8, 3],
       [7, 7, 1, 8],
       [9, 0, 0, 8]])

In [26]:
df = pd.DataFrame(nums, index = dates, columns = ['A', 'B', 'C', 'D'])

In [44]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

### Building a pandas dataframe from dictionary

In [203]:
data = {
    "A" : 1.0,
    "B" : pd.Timestamp("20230228190355"),
    "C" : np.array([3, 3 ,3, 3]),
    "D" : pd.Categorical(["good", "bad", "good", "good"]),
    "E" : "hello pandas"
}
data

{'A': 1.0,
 'B': Timestamp('2023-02-28 19:03:55'),
 'C': array([3, 3, 3, 3]),
 'D': ['good', 'bad', 'good', 'good']
 Categories (2, object): ['bad', 'good'],
 'E': 'hello pandas'}

In [204]:
df2 = pd.DataFrame(data)
df2

A                   B  C     D             E
0  1.0 2023-02-28 19:03:55  3  good  hello pandas
1  1.0 2023-02-28 19:03:55  3   bad  hello pandas
2  1.0 2023-02-28 19:03:55  3  good  hello pandas
3  1.0 2023-02-28 19:03:55  3  good  hello pandas

In [30]:
df2.dtypes

A           float64
B    datetime64[ns]
C             int64
D          category
E            object
dtype: object

### VIewing data

In [31]:
df2.head()

A                   B  C          D             E
0  1.0 2023-02-28 19:03:55  3       good  hello pandas
1  1.0 2023-02-28 19:03:55  3        bad  hello pandas
2  1.0 2023-02-28 19:03:55  3        avg  hello pandas
3  1.0 2023-02-28 19:03:55  3  very good  hello pandas

In [32]:
df2.tail(2)

A                   B  C          D             E
2  1.0 2023-02-28 19:03:55  3        avg  hello pandas
3  1.0 2023-02-28 19:03:55  3  very good  hello pandas

In [45]:
df.index

DatetimeIndex(['2023-02-28', '2023-03-01', '2023-03-02', '2023-03-03',
               '2023-03-04', '2023-03-05'],
              dtype='datetime64[ns]', freq='D')

### Columns and Index

In [34]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [35]:
df.index

DatetimeIndex(['2023-02-28', '2023-03-01', '2023-03-02', '2023-03-03',
               '2023-03-04', '2023-03-05'],
              dtype='datetime64[ns]', freq='D')

In [36]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [37]:
df.to_numpy()

array([[4, 0, 0, 6],
       [1, 4, 4, 2],
       [6, 5, 2, 5],
       [0, 4, 8, 3],
       [7, 7, 1, 8],
       [9, 0, 0, 8]])

## Importing Data in pandas

1. CSV FIles
df = pd.read_csv("path")

2. Hadoop Distributed File Systems
df = pd.read_hdf("path")


3. Excel


4. SQL

5. JSON



In [38]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [39]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   4.500000  3.333333  2.500000  5.333333
std    3.507136  2.804758  3.082207  2.503331
min    0.000000  0.000000  0.000000  2.000000
25%    1.750000  1.000000  0.250000  3.500000
50%    5.000000  4.000000  1.500000  5.500000
75%    6.750000  4.750000  3.500000  7.500000
max    9.000000  7.000000  8.000000  8.000000

#### Describe() works only for categorical data 

In [49]:
df2

A                   B  C          D             E
0  1.0 2023-02-28 19:03:55  3       good  hello pandas
1  1.0 2023-02-28 19:03:55  3        bad  hello pandas
2  1.0 2023-02-28 19:03:55  3        avg  hello pandas
3  1.0 2023-02-28 19:03:55  3  very good  hello pandas

In [47]:
df2.describe()

A    C
count  4.0  4.0
mean   1.0  3.0
std    0.0  0.0
min    1.0  3.0
25%    1.0  3.0
50%    1.0  3.0
75%    1.0  3.0
max    1.0  3.0

### Sort Index and values

In [50]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [52]:
df.sort_index(axis = 0, ascending = True)

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [53]:
df.sort_values(by = "A")

A  B  C  D
2023-03-03  0  4  8  3
2023-03-01  1  4  4  2
2023-02-28  4  0  0  6
2023-03-02  6  5  2  5
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

### Access a column Name

In [57]:
df["A"]

2023-02-28    4
2023-03-01    1
2023-03-02    6
2023-03-03    0
2023-03-04    7
2023-03-05    9
Freq: D, Name: A, dtype: int64

In [58]:
df.A

2023-02-28    4
2023-03-01    1
2023-03-02    6
2023-03-03    0
2023-03-04    7
2023-03-05    9
Freq: D, Name: A, dtype: int64

In [65]:
df[0 : 3]["A"]

2023-02-28    4
2023-03-01    1
2023-03-02    6
Freq: D, Name: A, dtype: int64

In [235]:
df[["A", "B"]]

A                   B
0  1.0 2023-02-28 19:03:55
1  1.0 2023-02-28 19:03:55
2  1.0 2023-02-28 19:03:55
3  1.0 2023-02-28 19:03:55

## Loc, at, iloc and iat

In [87]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [72]:
dates[3]

Timestamp('2023-03-03 00:00:00', freq='D')

In [89]:
df.loc[dates[3]]

A    0
B    4
C    8
D    3
Name: 2023-03-03 00:00:00, dtype: int64

In [79]:
df.loc[[dates[0], dates[4]], ["A", "B"]]

A  B
2023-02-28  4  0
2023-03-04  7  7

In [96]:
df.loc[dates[2], "C"]

2

#### at is faster than loc to get the single scaller value

In [97]:
df.at[dates[2], "C"]

2

In [98]:
nums

array([[4, 0, 0, 6],
       [1, 4, 4, 2],
       [6, 5, 2, 5],
       [0, 4, 8, 3],
       [7, 7, 1, 8],
       [9, 0, 0, 8]])

In [106]:
df.loc[dates[3] : , "B" : ]

B  C  D
2023-03-03  4  8  3
2023-03-04  7  1  8
2023-03-05  0  0  8

### Numpy like slicing using iloc

In [108]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [111]:
df.iloc[0 : 3, 0 : 3]

A  B  C
2023-02-28  4  0  0
2023-03-01  1  4  4
2023-03-02  6  5  2

In [117]:
df.at["20230228", "A"]

4

In [118]:
df.iat[0, 0]

4

In [116]:
nums[0, 0]

4

### Filtring pandas df with logical expressions

In [119]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [126]:
df[(df["A"] >= 4) & (df["B"] == 0)]

A  B  C  D
2023-02-28  4  0  0  6
2023-03-05  9  0  0  8

## NOTE -> Concept of copy works exactly the same

In [141]:
df2 = df.copy()

In [142]:
df2.iat[0, 0] = 400

In [143]:
df2

A  B  C  D
2023-02-28  400  0  0  6
2023-03-01    1  4  4  2
2023-03-02    6  5  2  5
2023-03-03    0  4  8  3
2023-03-04    7  7  1  8
2023-03-05    9  0  0  8

In [144]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [145]:
n = input()

10


In [148]:
df["D"]

2023-02-28    6
2023-03-01    2
2023-03-02    5
2023-03-03    3
2023-03-04    8
2023-03-05    8
Freq: D, Name: D, dtype: int64

In [150]:
df.shape[0]

6

In [164]:
df[["A", "B"]]

A  B
2023-02-28  4  0
2023-03-01  1  4
2023-03-02  6  5
2023-03-03  0  4
2023-03-04  7  7
2023-03-05  9  0

## Missing Values

Drop them
Fill them
find them

In [168]:
df3 = df[df < 6].copy()

In [169]:
df3

A    B    C    D
2023-02-28  4.0  0.0  0.0  NaN
2023-03-01  1.0  4.0  4.0  2.0
2023-03-02  NaN  5.0  2.0  5.0
2023-03-03  0.0  4.0  NaN  3.0
2023-03-04  NaN  NaN  1.0  NaN
2023-03-05  NaN  0.0  0.0  NaN

In [170]:
df3.isna()

A      B      C      D
2023-02-28  False  False  False   True
2023-03-01  False  False  False  False
2023-03-02   True  False  False  False
2023-03-03  False  False   True  False
2023-03-04   True   True  False   True
2023-03-05   True  False  False   True

In [171]:
df3.fillna(value = 10)

A     B     C     D
2023-02-28   4.0   0.0   0.0  10.0
2023-03-01   1.0   4.0   4.0   2.0
2023-03-02  10.0   5.0   2.0   5.0
2023-03-03   0.0   4.0  10.0   3.0
2023-03-04  10.0  10.0   1.0  10.0
2023-03-05  10.0   0.0   0.0  10.0

In [172]:
df3

A    B    C    D
2023-02-28  4.0  0.0  0.0  NaN
2023-03-01  1.0  4.0  4.0  2.0
2023-03-02  NaN  5.0  2.0  5.0
2023-03-03  0.0  4.0  NaN  3.0
2023-03-04  NaN  NaN  1.0  NaN
2023-03-05  NaN  0.0  0.0  NaN

In [179]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(axis: 'Axis' = 0, how: 'str' = 'any', thresh=None, subset: 'IndexLabel' = None, inplace: 'bool' = False) method of pandas.core.frame.DataFrame instance
    Remove missing values.
    
    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.
    
    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.
    
        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.
    
        .. versionchanged:: 1.0.0
    
           Pass tuple or list to drop on multiple axes.
           Only a single axis is allowed.
    
    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.
    
      

In [191]:
df3

A    B    C    D
2023-02-28  4.0  0.0  0.0  NaN
2023-03-01  1.0  4.0  4.0  2.0
2023-03-02  NaN  5.0  2.0  5.0
2023-03-03  0.0  4.0  NaN  3.0
2023-03-04  NaN  NaN  1.0  NaN
2023-03-05  NaN  0.0  0.0  NaN

### Drop all rows for which col A has NaN values

In [200]:
df3[df3["A"].isna() == False]

A    B    C    D
2023-02-28  4.0  0.0  0.0  NaN
2023-03-01  1.0  4.0  4.0  2.0
2023-03-03  0.0  4.0  NaN  3.0

## Apply

In [192]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [194]:
df.apply(lambda x : x ** 2)

A   B   C   D
2023-02-28  16   0   0  36
2023-03-01   1  16  16   4
2023-03-02  36  25   4  25
2023-03-03   0  16  64   9
2023-03-04  49  49   1  64
2023-03-05  81   0   0  64

A    B    C    D
2023-02-28  4.0  0.0  0.0  NaN
2023-03-01  1.0  4.0  4.0  2.0
2023-03-03  0.0  4.0  NaN  3.0

In [199]:
df3

A    B    C    D
2023-02-28  4.0  0.0  0.0  NaN
2023-03-01  1.0  4.0  4.0  2.0
2023-03-02  NaN  5.0  2.0  5.0
2023-03-03  0.0  4.0  NaN  3.0
2023-03-04  NaN  NaN  1.0  NaN
2023-03-05  NaN  0.0  0.0  NaN

## Histograming

In [205]:
data = {
    "A" : 1.0,
    "B" : pd.Timestamp("20230228190355"),
    "C" : np.array([3, 3 ,3, 3]),
    "D" : pd.Categorical(["good", "bad", "good", "good"]),
    "E" : "hello pandas"
}
data

{'A': 1.0,
 'B': Timestamp('2023-02-28 19:03:55'),
 'C': array([3, 3, 3, 3]),
 'D': ['good', 'bad', 'good', 'good']
 Categories (2, object): ['bad', 'good'],
 'E': 'hello pandas'}

In [206]:
df = pd.DataFrame(data)

In [207]:
df

A                   B  C     D             E
0  1.0 2023-02-28 19:03:55  3  good  hello pandas
1  1.0 2023-02-28 19:03:55  3   bad  hello pandas
2  1.0 2023-02-28 19:03:55  3  good  hello pandas
3  1.0 2023-02-28 19:03:55  3  good  hello pandas

In [209]:
df['D'].value_counts()

good    3
bad     1
Name: D, dtype: int64

In [210]:
df['D'].unique()

['good', 'bad']
Categories (2, object): ['bad', 'good']

## Merging two Data Frames

In [212]:
d1 = {
    "A" : [1, 2, 3],
    "B" : [4, 5, 6],
}

d2 = {
    "A" : [1, 2, 3],
    "C" : [7, 8, 9],
}

In [213]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [214]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [215]:
df2

A  C
0  1  7
1  2  8
2  3  9

In [216]:
pd.merge(df1, df2, on = "A")

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

## Concat two data frames

In [217]:
d1 = {
    "A" : [1, 2, 3],
    "B" : [4, 5, 6],
}

d2 = {
    "A" : [1, 2, 3],
    "B" : [7, 8, 9],
}

In [218]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [219]:
pd.concat([df1, df2])

A  B
0  1  4
1  2  5
2  3  6
0  1  7
1  2  8
2  3  9

In [220]:
df

A                   B  C     D             E
0  1.0 2023-02-28 19:03:55  3  good  hello pandas
1  1.0 2023-02-28 19:03:55  3   bad  hello pandas
2  1.0 2023-02-28 19:03:55  3  good  hello pandas
3  1.0 2023-02-28 19:03:55  3  good  hello pandas

In [227]:
df.groupby("D")["C"].sum()

D
bad     3
good    9
Name: C, dtype: int64

In [228]:
df["E"] = [1, 2, 3, 4]

In [229]:
df

A                   B  C     D  E
0  1.0 2023-02-28 19:03:55  3  good  1
1  1.0 2023-02-28 19:03:55  3   bad  2
2  1.0 2023-02-28 19:03:55  3  good  3
3  1.0 2023-02-28 19:03:55  3  good  4

In [233]:
df.groupby("D")[["C", "E"]].sum()

C  E
D         
bad   3  2
good  9  8