In [20]:
import numpy as np
import pandas as pd

In [21]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [22]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [23]:
dates = pd.date_range('20230228', periods = 6)
dates

DatetimeIndex(['2023-02-28', '2023-03-01', '2023-03-02', '2023-03-03',
               '2023-03-04', '2023-03-05'],
              dtype='datetime64[ns]', freq='D')

In [24]:
rng = np.random.default_rng()

In [25]:
nums = rng.integers(10, size = (6, 4))
nums

array([[4, 0, 0, 6],
       [1, 4, 4, 2],
       [6, 5, 2, 5],
       [0, 4, 8, 3],
       [7, 7, 1, 8],
       [9, 0, 0, 8]])

In [26]:
df = pd.DataFrame(nums, index = dates, columns = ['A', 'B', 'C', 'D'])

In [27]:
df.dtypes

A    int64
B    int64
C    int64
D    int64
dtype: object

### Building a pandas dataframe from dictionary

In [28]:
data = {
    "A" : 1.0,
    "B" : pd.Timestamp("20230228190355"),
    "C" : np.array([3, 3 ,3, 3]),
    "D" : pd.Categorical(["good", "bad", "avg", "very good"]),
    "E" : "hello pandas"
}
data

{'A': 1.0,
 'B': Timestamp('2023-02-28 19:03:55'),
 'C': array([3, 3, 3, 3]),
 'D': ['good', 'bad', 'avg', 'very good']
 Categories (4, object): ['avg', 'bad', 'good', 'very good'],
 'E': 'hello pandas'}

In [29]:
df2 = pd.DataFrame(data)
df2

A                   B  C          D             E
0  1.0 2023-02-28 19:03:55  3       good  hello pandas
1  1.0 2023-02-28 19:03:55  3        bad  hello pandas
2  1.0 2023-02-28 19:03:55  3        avg  hello pandas
3  1.0 2023-02-28 19:03:55  3  very good  hello pandas

In [30]:
df2.dtypes

A           float64
B    datetime64[ns]
C             int64
D          category
E            object
dtype: object

### VIewing data

In [31]:
df2.head()

A                   B  C          D             E
0  1.0 2023-02-28 19:03:55  3       good  hello pandas
1  1.0 2023-02-28 19:03:55  3        bad  hello pandas
2  1.0 2023-02-28 19:03:55  3        avg  hello pandas
3  1.0 2023-02-28 19:03:55  3  very good  hello pandas

In [32]:
df2.tail(2)

A                   B  C          D             E
2  1.0 2023-02-28 19:03:55  3        avg  hello pandas
3  1.0 2023-02-28 19:03:55  3  very good  hello pandas

In [33]:
df2.index

RangeIndex(start=0, stop=4, step=1)

### Columns and Index

In [34]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [35]:
df.index

DatetimeIndex(['2023-02-28', '2023-03-01', '2023-03-02', '2023-03-03',
               '2023-03-04', '2023-03-05'],
              dtype='datetime64[ns]', freq='D')

In [36]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [37]:
df.to_numpy()

array([[4, 0, 0, 6],
       [1, 4, 4, 2],
       [6, 5, 2, 5],
       [0, 4, 8, 3],
       [7, 7, 1, 8],
       [9, 0, 0, 8]])

## Importing Data in pandas

1. CSV FIles
df = pd.read_csv("path")

2. Hadoop Distributed File Systems
df = pd.read_hdf("path")


3. Excel


4. SQL

5. JSON



In [38]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [39]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   4.500000  3.333333  2.500000  5.333333
std    3.507136  2.804758  3.082207  2.503331
min    0.000000  0.000000  0.000000  2.000000
25%    1.750000  1.000000  0.250000  3.500000
50%    5.000000  4.000000  1.500000  5.500000
75%    6.750000  4.750000  3.500000  7.500000
max    9.000000  7.000000  8.000000  8.000000

In [40]:
df

A  B  C  D
2023-02-28  4  0  0  6
2023-03-01  1  4  4  2
2023-03-02  6  5  2  5
2023-03-03  0  4  8  3
2023-03-04  7  7  1  8
2023-03-05  9  0  0  8

In [41]:
df<TAB>

SyntaxError: invalid syntax (<ipython-input-41-fdcf42f0f592>, line 1)