# Numpy Basics

### Install numpy

In [1]:
!pip3 install numpy

### Import numpy

In [2]:
import numpy as np

### Initialise a ndarray from a python list

In [5]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [6]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [7]:
a = np.array([[1, 2, 3], [2, 3, 4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
a[0]

array([1, 2, 3])

### Some important methods to initialise ndarrays

In [11]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.empty(4)

array([1.89094575e-316, 0.00000000e+000, 7.90505033e-323, 7.90505033e-323])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

### Generate a range of numbers from start to end with some step size

In [19]:
np.arange(2, 21, 4)

array([ 2,  6, 10, 14, 18])

### Generate k numbers from start to end

In [24]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

Numpy array data type (dtype)

In [27]:
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)